name: movieflix
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A carousel slider widget.
  carousel_slider: ^4.2.1
  # Show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.4.0
  # Discover network connectivity
  connectivity_plus: ^6.0.4
  # Lib Icons
  cupertino_icons: ^1.0.6
  # HTTP networking package
  dio: ^5.5.0+1
  # Error handling and railway oriented programming
  either_dart: ^1.0.0
  # Compare objects
  equatable: ^2.0.5
  # To initially only show a defined number of lines of a probably long text
  expandable_richtext: ^1.0.7
  # Bloc state management
  flutter_bloc: ^8.1.6
  # Change Launcher Icon
  flutter_launcher_icons: ^0.13.1
  # Modularized routes and Modularized Dependency Injection
  flutter_modular: ^6.3.4
  # Change Native Splash
  flutter_native_splash: ^2.4.1
  # To use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # Provides internationalization and localization facilities
  intl: ^0.19.0
  # Dio interceptor that logs network
  pretty_dio_logger: ^1.4.0
  # Loading shimmer effect
  shimmer: ^3.0.0
  # Create responsive UI easily
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/launcher/
