name: movieflix
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # Change Launcher Icon
  flutter_launcher_icons: ^0.13.1
  # Modularized routes and Modularized Dependency Injection
  flutter_modular: ^6.3.4
  # Change Native Splash
  flutter_native_splash: ^2.4.1
  # Create responsive UI easily
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
