// Mocks generated by Mockito 5.4.4 from annotations
// in movieflix/test/features/details/data/repositories/details_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movieflix/features/details/data/datasources/details_datasource.dart'
    as _i3;
import 'package:movieflix/features/details/data/models/cast/response_cast_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseCastModel_0 extends _i1.SmartFake
    implements _i2.ResponseCastModel {
  _FakeResponseCastModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DetailsDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailsDatasource extends _i1.Mock implements _i3.DetailsDatasource {
  MockDetailsDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseCastModel> getMovieCast({required int? movieId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieCast,
          [],
          {#movieId: movieId},
        ),
        returnValue:
            _i4.Future<_i2.ResponseCastModel>.value(_FakeResponseCastModel_0(
          this,
          Invocation.method(
            #getMovieCast,
            [],
            {#movieId: movieId},
          ),
        )),
      ) as _i4.Future<_i2.ResponseCastModel>);
}
